package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"

	"github.com/DavidHoenisch/remotr/internal/ubuntuproqualification"
)

func main() {
	source := flag.String("source", "", "qualification manifest")
	output := flag.String("output", "", "generated Go output")
	check := flag.Bool("check", false, "fail when generated output differs")
	flag.Parse()
	if *source == "" || *output == "" {
		fatalf("source and output are required")
	}
	raw, err := os.ReadFile(*source) // #nosec G304 -- explicit checked-in generator input.
	if err != nil {
		fatalf("read source: %v", err)
	}
	if _, err := ubuntuproqualification.Decode(raw); err != nil {
		fatalf("validate source: %v", err)
	}
	sum := sha256.Sum256(raw)
	generated, err := format.Source([]byte(fmt.Sprintf(`// Code generated by internal/releasecatalog/cmd/generate; DO NOT EDIT.
package releasecatalog

const generatedUbuntuProSourceSHA256 = %s
var generatedUbuntuProYAML = []byte(%s)
`, strconv.Quote(fmt.Sprintf("%x", sum)), strconv.Quote(string(raw)))))
	if err != nil {
		fatalf("format output: %v", err)
	}
	if *check {
		existing, err := os.ReadFile(*output) // #nosec G304 -- explicit generated output.
		if err != nil || !bytes.Equal(existing, generated) {
			fatalf("generated release catalog is stale; run go generate ./internal/releasecatalog")
		}
		return
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil { // #nosec G306 -- checked-in source artifact.
		fatalf("write output: %v", err)
	}
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "release catalog: "+format+"\n", args...)
	os.Exit(1)
}
