// Code generated by internal/releasecatalog/cmd/generate-releases; DO NOT EDIT.
package releasecatalog

const generatedAgentReleasesSourceSHA256 = "62bad9e7802f281e643c69aed8fcd4b0949fc49334d4b0888ad5d5caac5f0421"

var generatedAgentReleasesYAML = []byte("version: 1\nreleases:\n  - version: v0.1.13\n    capability_document: false\n    upgrade_eligible: true\n    integrity: sha256-manifest\n    schemas: [0]\n    platforms: [linux]\n    architectures: [x86, arm]\n  - version: v0.6.8\n    capability_document: true\n    upgrade_eligible: true\n    integrity: sha256-manifest\n    schemas: [0, 1]\n    platforms: [linux]\n    architectures: [x86, arm]\n  - version: v0.6.9\n    capability_document: true\n    upgrade_eligible: true\n    integrity: sha256-manifest\n    schemas: [0, 1]\n    platforms: [linux]\n    architectures: [x86, arm]\n  - version: v0.6.10\n    capability_document: true\n    upgrade_eligible: true\n    integrity: sha256-manifest\n    schemas: [0, 1]\n    platforms: [linux]\n    architectures: [x86, arm]\n")
