// Code generated by internal/releasecatalog/cmd/generate-releases; DO NOT EDIT.
package releasecatalog

const generatedAgentReleasesSourceSHA256 = "c5f666060a5e94b3a329a3272b3beef2221c64b39b60248666b1823db2c1dab5"

var generatedAgentReleasesYAML = []byte("version: 1\nreleases:\n  - version: v0.1.13\n    capability_document: false\n    upgrade_eligible: true\n    integrity: sha256-manifest\n    schemas: [0]\n    platforms: [linux]\n    architectures: [x86, arm]\n  - version: v0.6.8\n    capability_document: true\n    upgrade_eligible: true\n    integrity: sha256-manifest\n    schemas: [0, 1]\n    platforms: [linux]\n    architectures: [x86, arm]\n  - version: v0.6.9\n    capability_document: true\n    upgrade_eligible: true\n    integrity: sha256-manifest\n    schemas: [0, 1]\n    platforms: [linux]\n    architectures: [x86, arm]\n")
