Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.hostname = "remotr-firewall-test"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "remotr-firewall-test"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.synced_folder "../..", "/workspace"
  config.vm.provision "shell", path: "provision.sh"
end
