Vagrant.configure("2") do |config|
  config.vm.box = ENV.fetch("REMOTR_VM_BOX", "generic/debian12")
  config.vm.box_version = ENV.fetch("REMOTR_VM_BOX_VERSION", "4.3.12")
  config.vm.box_check_update = false
  config.vm.boot_timeout = ENV.fetch("REMOTR_VM_BOOT_TIMEOUT", "600").to_i
  config.vm.hostname = ENV.fetch("REMOTR_VM_HOSTNAME", "remotr-provider-test")
  config.ssh.insert_key = true

  config.vm.provider "libvirt" do |libvirt|
    libvirt.driver = "qemu"
    libvirt.uri = "qemu:///system"
    libvirt.management_network_name = "remotr-provider-safety"
    libvirt.management_network_address = "192.168.231.0/24"
    libvirt.management_network_mode = "nat"
    libvirt.management_network_keep = true
    libvirt.machine_virtual_size = 128
    libvirt.memory = 2048
    libvirt.cpus = 2
  end

  if ["ubuntu-pro", "core-delivery"].include?(ENV.fetch("REMOTR_VM_PROFILE", "default"))
    config.vm.synced_folder ".", "/vagrant", disabled: true
  else
    config.vm.synced_folder "../..", "/workspace", type: "rsync", rsync__auto: false, rsync__exclude: ["compose/runtime"]
  end
  config.vm.provision "shell",
    path: "provision.sh",
    env: { "REMOTR_VM_PROFILE" => ENV.fetch("REMOTR_VM_PROFILE", "default") }
end
