// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_upgrade.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearEndpointDesiredAgentVersion = `-- name: ClearEndpointDesiredAgentVersion :one
UPDATE endpoints
SET desired_agent_version = NULL,
    desired_agent_version_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, fleet, cert_fingerprint, desired_agent_version, desired_agent_version_at, reported_agent_version, agent_upgrade_phase, agent_upgrade_message, agent_upgrade_reported_at, created_at, updated_at
`

func (q *Queries) ClearEndpointDesiredAgentVersion(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, clearEndpointDesiredAgentVersion, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Fleet,
		&i.CertFingerprint,
		&i.DesiredAgentVersion,
		&i.DesiredAgentVersionAt,
		&i.ReportedAgentVersion,
		&i.AgentUpgradePhase,
		&i.AgentUpgradeMessage,
		&i.AgentUpgradeReportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEndpointDesiredAgentVersion = `-- name: SetEndpointDesiredAgentVersion :one
UPDATE endpoints
SET desired_agent_version = $2,
    desired_agent_version_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, fleet, cert_fingerprint, desired_agent_version, desired_agent_version_at, reported_agent_version, agent_upgrade_phase, agent_upgrade_message, agent_upgrade_reported_at, created_at, updated_at
`

type SetEndpointDesiredAgentVersionParams struct {
	ID                  string
	DesiredAgentVersion pgtype.Text
}

func (q *Queries) SetEndpointDesiredAgentVersion(ctx context.Context, arg SetEndpointDesiredAgentVersionParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, setEndpointDesiredAgentVersion, arg.ID, arg.DesiredAgentVersion)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Fleet,
		&i.CertFingerprint,
		&i.DesiredAgentVersion,
		&i.DesiredAgentVersionAt,
		&i.ReportedAgentVersion,
		&i.AgentUpgradePhase,
		&i.AgentUpgradeMessage,
		&i.AgentUpgradeReportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setFleetDesiredAgentVersion = `-- name: SetFleetDesiredAgentVersion :execrows
UPDATE endpoints
SET desired_agent_version = $2,
    desired_agent_version_at = now(),
    updated_at = now()
WHERE fleet = $1
`

type SetFleetDesiredAgentVersionParams struct {
	Fleet               string
	DesiredAgentVersion pgtype.Text
}

func (q *Queries) SetFleetDesiredAgentVersion(ctx context.Context, arg SetFleetDesiredAgentVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFleetDesiredAgentVersion, arg.Fleet, arg.DesiredAgentVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEndpointAgentUpgradeReport = `-- name: UpdateEndpointAgentUpgradeReport :one
UPDATE endpoints
SET reported_agent_version = $2,
    agent_upgrade_phase = $3,
    agent_upgrade_message = $4,
    agent_upgrade_reported_at = now(),
    desired_agent_version = CASE
        WHEN $5::boolean THEN NULL
        ELSE desired_agent_version
    END,
    desired_agent_version_at = CASE
        WHEN $5::boolean THEN NULL
        ELSE desired_agent_version_at
    END,
    updated_at = now()
WHERE id = $1
RETURNING id, fleet, cert_fingerprint, desired_agent_version, desired_agent_version_at, reported_agent_version, agent_upgrade_phase, agent_upgrade_message, agent_upgrade_reported_at, created_at, updated_at
`

type UpdateEndpointAgentUpgradeReportParams struct {
	ID                   string
	ReportedAgentVersion pgtype.Text
	AgentUpgradePhase    pgtype.Text
	AgentUpgradeMessage  pgtype.Text
	Column5              bool
}

func (q *Queries) UpdateEndpointAgentUpgradeReport(ctx context.Context, arg UpdateEndpointAgentUpgradeReportParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpointAgentUpgradeReport,
		arg.ID,
		arg.ReportedAgentVersion,
		arg.AgentUpgradePhase,
		arg.AgentUpgradeMessage,
		arg.Column5,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Fleet,
		&i.CertFingerprint,
		&i.DesiredAgentVersion,
		&i.DesiredAgentVersionAt,
		&i.ReportedAgentVersion,
		&i.AgentUpgradePhase,
		&i.AgentUpgradeMessage,
		&i.AgentUpgradeReportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
