// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_packages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppPackage = `-- name: CreateAppPackage :one
INSERT INTO app_packages (id, name, version, s3_key, sha256, manifest)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, version, s3_key, sha256, manifest, created_at
`

type CreateAppPackageParams struct {
	ID       pgtype.UUID
	Name     string
	Version  string
	S3Key    string
	Sha256   string
	Manifest []byte
}

func (q *Queries) CreateAppPackage(ctx context.Context, arg CreateAppPackageParams) (AppPackage, error) {
	row := q.db.QueryRow(ctx, createAppPackage,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.S3Key,
		arg.Sha256,
		arg.Manifest,
	)
	var i AppPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.S3Key,
		&i.Sha256,
		&i.Manifest,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAppPackage = `-- name: DeleteAppPackage :execrows
DELETE FROM app_packages
WHERE name = $1 AND version = $2
`

type DeleteAppPackageParams struct {
	Name    string
	Version string
}

func (q *Queries) DeleteAppPackage(ctx context.Context, arg DeleteAppPackageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppPackage, arg.Name, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppPackage = `-- name: GetAppPackage :one
SELECT id, name, version, s3_key, sha256, manifest, created_at
FROM app_packages
WHERE name = $1 AND version = $2
`

type GetAppPackageParams struct {
	Name    string
	Version string
}

func (q *Queries) GetAppPackage(ctx context.Context, arg GetAppPackageParams) (AppPackage, error) {
	row := q.db.QueryRow(ctx, getAppPackage, arg.Name, arg.Version)
	var i AppPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.S3Key,
		&i.Sha256,
		&i.Manifest,
		&i.CreatedAt,
	)
	return i, err
}

const listAppPackages = `-- name: ListAppPackages :many
SELECT id, name, version, s3_key, sha256, manifest, created_at
FROM app_packages
WHERE ($1::text = '' OR name LIKE $1 || '%')
ORDER BY name, version
`

func (q *Queries) ListAppPackages(ctx context.Context, dollar_1 string) ([]AppPackage, error) {
	rows, err := q.db.Query(ctx, listAppPackages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPackage{}
	for rows.Next() {
		var i AppPackage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.S3Key,
			&i.Sha256,
			&i.Manifest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
