// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apply_failures.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertApplyFailure = `-- name: InsertApplyFailure :exec
INSERT INTO apply_failures (id, endpoint_id, release_ref, resource_address, message, reported_at)
VALUES ($1, $2, $3, $4, $5, now())
`

type InsertApplyFailureParams struct {
	ID              pgtype.UUID
	EndpointID      pgtype.UUID
	ReleaseRef      string
	ResourceAddress string
	Message         string
}

func (q *Queries) InsertApplyFailure(ctx context.Context, arg InsertApplyFailureParams) error {
	_, err := q.db.Exec(ctx, insertApplyFailure,
		arg.ID,
		arg.EndpointID,
		arg.ReleaseRef,
		arg.ResourceAddress,
		arg.Message,
	)
	return err
}
