// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apply_failures.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestApplyFailure = `-- name: GetLatestApplyFailure :one
SELECT id, endpoint_id, release_ref, resource_address, message, reported_at
FROM apply_failures
WHERE endpoint_id = $1
ORDER BY reported_at DESC
LIMIT 1
`

func (q *Queries) GetLatestApplyFailure(ctx context.Context, endpointID string) (ApplyFailure, error) {
	row := q.db.QueryRow(ctx, getLatestApplyFailure, endpointID)
	var i ApplyFailure
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.ReleaseRef,
		&i.ResourceAddress,
		&i.Message,
		&i.ReportedAt,
	)
	return i, err
}

const insertApplyFailure = `-- name: InsertApplyFailure :exec
INSERT INTO apply_failures (id, endpoint_id, release_ref, resource_address, message, reported_at)
VALUES ($1, $2, $3, $4, $5, now())
`

type InsertApplyFailureParams struct {
	ID              pgtype.UUID
	EndpointID      string
	ReleaseRef      string
	ResourceAddress string
	Message         string
}

func (q *Queries) InsertApplyFailure(ctx context.Context, arg InsertApplyFailureParams) error {
	_, err := q.db.Exec(ctx, insertApplyFailure,
		arg.ID,
		arg.EndpointID,
		arg.ReleaseRef,
		arg.ResourceAddress,
		arg.Message,
	)
	return err
}
