// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    id, occurred_at, request_id, actor_type, actor_id, actor_fingerprint,
    action, method, path, status_code, resource_type, resource_id, client_ip, details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type InsertAuditEventParams struct {
	ID               pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	RequestID        pgtype.Text
	ActorType        string
	ActorID          pgtype.Text
	ActorFingerprint pgtype.Text
	Action           string
	Method           string
	Path             string
	StatusCode       int32
	ResourceType     pgtype.Text
	ResourceID       pgtype.Text
	ClientIp         pgtype.Text
	Details          []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.OccurredAt,
		arg.RequestID,
		arg.ActorType,
		arg.ActorID,
		arg.ActorFingerprint,
		arg.Action,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.ResourceType,
		arg.ResourceID,
		arg.ClientIp,
		arg.Details,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT
    id, occurred_at, request_id, actor_type, actor_id, actor_fingerprint,
    action, method, path, status_code, resource_type, resource_id, client_ip, details
FROM audit_events
WHERE ($1::timestamptz IS NULL OR occurred_at >= $1)
  AND ($2::timestamptz IS NULL OR occurred_at <= $2)
  AND ($3::text IS NULL OR $3 = '' OR action = $3)
  AND ($4::text IS NULL OR $4 = '' OR actor_type = $4)
  AND (
    $5::timestamptz IS NULL OR $6::uuid IS NULL
    OR (occurred_at, id) < ($5, $6)
  )
ORDER BY occurred_at DESC, id DESC
LIMIT $7
`

type ListAuditEventsParams struct {
	Since     pgtype.Timestamptz
	Until     pgtype.Timestamptz
	Action    pgtype.Text
	ActorType pgtype.Text
	CursorAt  pgtype.Timestamptz
	CursorID  pgtype.UUID
	Limit     int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.Since,
		arg.Until,
		arg.Action,
		arg.ActorType,
		arg.CursorAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.RequestID,
			&i.ActorType,
			&i.ActorID,
			&i.ActorFingerprint,
			&i.Action,
			&i.Method,
			&i.Path,
			&i.StatusCode,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClientIp,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
