// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_control.sql

package db

import "context"

const loadChangeControlState = `-- name: LoadChangeControlState :one
SELECT state_json, revision
FROM change_control_state
WHERE singleton = TRUE
`

type LoadChangeControlStateRow struct {
	StateJson []byte
	Revision  int64
}

func (q *Queries) LoadChangeControlState(ctx context.Context) (LoadChangeControlStateRow, error) {
	row := q.db.QueryRow(ctx, loadChangeControlState)
	var result LoadChangeControlStateRow
	err := row.Scan(&result.StateJson, &result.Revision)
	return result, err
}

const saveChangeControlState = `-- name: SaveChangeControlState :one
WITH updated AS (
    UPDATE change_control_state
    SET state_json = $1,
        revision = revision + 1,
        updated_at = now()
    WHERE singleton = TRUE
      AND revision = $2
    RETURNING revision
), inserted AS (
    INSERT INTO change_control_state (singleton, state_json, revision, updated_at)
    SELECT TRUE, $1, 1, now()
    WHERE $2 = 0
      AND NOT EXISTS (SELECT 1 FROM updated)
    ON CONFLICT (singleton) DO NOTHING
    RETURNING revision
)
SELECT revision FROM updated
UNION ALL
SELECT revision FROM inserted
`

type SaveChangeControlStateParams struct {
	StateJson        []byte
	ExpectedRevision int64
}

func (q *Queries) SaveChangeControlState(ctx context.Context, arg SaveChangeControlStateParams) (int64, error) {
	row := q.db.QueryRow(ctx, saveChangeControlState, arg.StateJson, arg.ExpectedRevision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
