// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compiled_artifact_variants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertCompiledArtifactVariantForFleet = `-- name: UpsertCompiledArtifactVariantForFleet :one
INSERT INTO compiled_artifact_variants (
    fleet_name, endpoint_id, release_ref, artifact_type, schema_version,
    source_digest, requirement_set_digest, requirement_set, artifact, digest, compiled_at
) VALUES (
    $1, NULL, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (fleet_name, release_ref, artifact_type, schema_version, requirement_set_digest)
    WHERE fleet_name IS NOT NULL
DO UPDATE SET
    source_digest = EXCLUDED.source_digest,
    requirement_set = EXCLUDED.requirement_set,
    artifact = EXCLUDED.artifact,
    digest = EXCLUDED.digest,
    compiled_at = NOW()
RETURNING id, fleet_name, endpoint_id, release_ref, artifact_type, schema_version, source_digest, requirement_set_digest, requirement_set, artifact, digest, compiled_at
`

type UpsertCompiledArtifactVariantForFleetParams struct {
	FleetName            pgtype.Text
	ReleaseRef           string
	ArtifactType         string
	SchemaVersion        int32
	SourceDigest         string
	RequirementSetDigest string
	RequirementSet       []byte
	Artifact             []byte
	Digest               string
}

func (q *Queries) UpsertCompiledArtifactVariantForFleet(ctx context.Context, arg UpsertCompiledArtifactVariantForFleetParams) (CompiledArtifactVariant, error) {
	row := q.db.QueryRow(ctx, upsertCompiledArtifactVariantForFleet,
		arg.FleetName, arg.ReleaseRef, arg.ArtifactType, arg.SchemaVersion,
		arg.SourceDigest, arg.RequirementSetDigest, arg.RequirementSet, arg.Artifact, arg.Digest,
	)
	return scanCompiledArtifactVariant(row)
}

const upsertCompiledArtifactVariantForEndpoint = `-- name: UpsertCompiledArtifactVariantForEndpoint :one
INSERT INTO compiled_artifact_variants (
    fleet_name, endpoint_id, release_ref, artifact_type, schema_version,
    source_digest, requirement_set_digest, requirement_set, artifact, digest, compiled_at
) VALUES (
    NULL, $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (endpoint_id, release_ref, artifact_type, schema_version, requirement_set_digest)
    WHERE endpoint_id IS NOT NULL
DO UPDATE SET
    source_digest = EXCLUDED.source_digest,
    requirement_set = EXCLUDED.requirement_set,
    artifact = EXCLUDED.artifact,
    digest = EXCLUDED.digest,
    compiled_at = NOW()
RETURNING id, fleet_name, endpoint_id, release_ref, artifact_type, schema_version, source_digest, requirement_set_digest, requirement_set, artifact, digest, compiled_at
`

type UpsertCompiledArtifactVariantForEndpointParams struct {
	EndpointID           pgtype.Text
	ReleaseRef           string
	ArtifactType         string
	SchemaVersion        int32
	SourceDigest         string
	RequirementSetDigest string
	RequirementSet       []byte
	Artifact             []byte
	Digest               string
}

func (q *Queries) UpsertCompiledArtifactVariantForEndpoint(ctx context.Context, arg UpsertCompiledArtifactVariantForEndpointParams) (CompiledArtifactVariant, error) {
	row := q.db.QueryRow(ctx, upsertCompiledArtifactVariantForEndpoint,
		arg.EndpointID, arg.ReleaseRef, arg.ArtifactType, arg.SchemaVersion,
		arg.SourceDigest, arg.RequirementSetDigest, arg.RequirementSet, arg.Artifact, arg.Digest,
	)
	return scanCompiledArtifactVariant(row)
}

const listCompiledArtifactVariantsForFleet = `-- name: ListCompiledArtifactVariantsForFleet :many
SELECT id, fleet_name, endpoint_id, release_ref, artifact_type, schema_version, source_digest, requirement_set_digest, requirement_set, artifact, digest, compiled_at
FROM compiled_artifact_variants
WHERE fleet_name = $1 AND release_ref = $2 AND artifact_type = $3
ORDER BY schema_version DESC, requirement_set_digest
`

type ListCompiledArtifactVariantsForFleetParams struct {
	FleetName    pgtype.Text
	ReleaseRef   string
	ArtifactType string
}

func (q *Queries) ListCompiledArtifactVariantsForFleet(ctx context.Context, arg ListCompiledArtifactVariantsForFleetParams) ([]CompiledArtifactVariant, error) {
	rows, err := q.db.Query(ctx, listCompiledArtifactVariantsForFleet, arg.FleetName, arg.ReleaseRef, arg.ArtifactType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompiledArtifactVariant
	for rows.Next() {
		item, err := scanCompiledArtifactVariant(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

const listCompiledArtifactVariantsForEndpoint = `-- name: ListCompiledArtifactVariantsForEndpoint :many
SELECT id, fleet_name, endpoint_id, release_ref, artifact_type, schema_version, source_digest, requirement_set_digest, requirement_set, artifact, digest, compiled_at
FROM compiled_artifact_variants
WHERE endpoint_id = $1 AND release_ref = $2 AND artifact_type = $3
ORDER BY schema_version DESC, requirement_set_digest
`

type ListCompiledArtifactVariantsForEndpointParams struct {
	EndpointID   pgtype.Text
	ReleaseRef   string
	ArtifactType string
}

func (q *Queries) ListCompiledArtifactVariantsForEndpoint(ctx context.Context, arg ListCompiledArtifactVariantsForEndpointParams) ([]CompiledArtifactVariant, error) {
	rows, err := q.db.Query(ctx, listCompiledArtifactVariantsForEndpoint, arg.EndpointID, arg.ReleaseRef, arg.ArtifactType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompiledArtifactVariant
	for rows.Next() {
		item, err := scanCompiledArtifactVariant(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

const pruneOldCompiledArtifactVariants = `-- name: PruneOldCompiledArtifactVariants :exec
DELETE FROM compiled_artifact_variants WHERE compiled_at < $1
`

func (q *Queries) PruneOldCompiledArtifactVariants(ctx context.Context, compiledAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, pruneOldCompiledArtifactVariants, compiledAt)
	return err
}

type compiledArtifactVariantScanner interface {
	Scan(dest ...any) error
}

func scanCompiledArtifactVariant(row compiledArtifactVariantScanner) (CompiledArtifactVariant, error) {
	var item CompiledArtifactVariant
	err := row.Scan(
		&item.ID, &item.FleetName, &item.EndpointID, &item.ReleaseRef, &item.ArtifactType,
		&item.SchemaVersion, &item.SourceDigest, &item.RequirementSetDigest, &item.RequirementSet,
		&item.Artifact, &item.Digest, &item.CompiledAt,
	)
	return item, err
}
