// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compiled_artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompiledArtifactForEndpoint = `-- name: GetCompiledArtifactForEndpoint :one
SELECT artifact, digest
FROM compiled_artifacts
WHERE endpoint_id = $1
  AND release_ref = $2
  AND artifact_type = $3
`

type GetCompiledArtifactForEndpointParams struct {
	EndpointID   pgtype.Text
	ReleaseRef   string
	ArtifactType string
}

type GetCompiledArtifactForEndpointRow struct {
	Artifact []byte
	Digest   string
}

func (q *Queries) GetCompiledArtifactForEndpoint(ctx context.Context, arg GetCompiledArtifactForEndpointParams) (GetCompiledArtifactForEndpointRow, error) {
	row := q.db.QueryRow(ctx, getCompiledArtifactForEndpoint, arg.EndpointID, arg.ReleaseRef, arg.ArtifactType)
	var i GetCompiledArtifactForEndpointRow
	err := row.Scan(&i.Artifact, &i.Digest)
	return i, err
}

const getCompiledArtifactForFleet = `-- name: GetCompiledArtifactForFleet :one
SELECT artifact, digest
FROM compiled_artifacts
WHERE fleet_name = $1
  AND release_ref = $2
  AND artifact_type = $3
`

type GetCompiledArtifactForFleetParams struct {
	FleetName    pgtype.Text
	ReleaseRef   string
	ArtifactType string
}

type GetCompiledArtifactForFleetRow struct {
	Artifact []byte
	Digest   string
}

func (q *Queries) GetCompiledArtifactForFleet(ctx context.Context, arg GetCompiledArtifactForFleetParams) (GetCompiledArtifactForFleetRow, error) {
	row := q.db.QueryRow(ctx, getCompiledArtifactForFleet, arg.FleetName, arg.ReleaseRef, arg.ArtifactType)
	var i GetCompiledArtifactForFleetRow
	err := row.Scan(&i.Artifact, &i.Digest)
	return i, err
}

const pruneOldCompiledArtifacts = `-- name: PruneOldCompiledArtifacts :exec
DELETE FROM compiled_artifacts
WHERE compiled_at < $1
`

func (q *Queries) PruneOldCompiledArtifacts(ctx context.Context, compiledAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, pruneOldCompiledArtifacts, compiledAt)
	return err
}

const upsertCompiledArtifactForEndpoint = `-- name: UpsertCompiledArtifactForEndpoint :one
INSERT INTO compiled_artifacts (
    fleet_name,
    endpoint_id,
    release_ref,
    artifact_type,
    artifact,
    digest,
    compiled_at
) VALUES (
    NULL,
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW()
)
ON CONFLICT (endpoint_id, release_ref, artifact_type)
    WHERE endpoint_id IS NOT NULL
DO UPDATE SET
    artifact = EXCLUDED.artifact,
    digest = EXCLUDED.digest,
    compiled_at = NOW()
RETURNING id, fleet_name, endpoint_id, release_ref, artifact_type, artifact, digest, compiled_at
`

type UpsertCompiledArtifactForEndpointParams struct {
	EndpointID   pgtype.Text
	ReleaseRef   string
	ArtifactType string
	Artifact     []byte
	Digest       string
}

func (q *Queries) UpsertCompiledArtifactForEndpoint(ctx context.Context, arg UpsertCompiledArtifactForEndpointParams) (CompiledArtifact, error) {
	row := q.db.QueryRow(ctx, upsertCompiledArtifactForEndpoint,
		arg.EndpointID,
		arg.ReleaseRef,
		arg.ArtifactType,
		arg.Artifact,
		arg.Digest,
	)
	var i CompiledArtifact
	err := row.Scan(
		&i.ID,
		&i.FleetName,
		&i.EndpointID,
		&i.ReleaseRef,
		&i.ArtifactType,
		&i.Artifact,
		&i.Digest,
		&i.CompiledAt,
	)
	return i, err
}

const upsertCompiledArtifactForFleet = `-- name: UpsertCompiledArtifactForFleet :one
INSERT INTO compiled_artifacts (
    fleet_name,
    endpoint_id,
    release_ref,
    artifact_type,
    artifact,
    digest,
    compiled_at
) VALUES (
    $1,
    NULL,
    $2,
    $3,
    $4,
    $5,
    NOW()
)
ON CONFLICT (fleet_name, release_ref, artifact_type)
    WHERE fleet_name IS NOT NULL
DO UPDATE SET
    artifact = EXCLUDED.artifact,
    digest = EXCLUDED.digest,
    compiled_at = NOW()
RETURNING id, fleet_name, endpoint_id, release_ref, artifact_type, artifact, digest, compiled_at
`

type UpsertCompiledArtifactForFleetParams struct {
	FleetName    pgtype.Text
	ReleaseRef   string
	ArtifactType string
	Artifact     []byte
	Digest       string
}

func (q *Queries) UpsertCompiledArtifactForFleet(ctx context.Context, arg UpsertCompiledArtifactForFleetParams) (CompiledArtifact, error) {
	row := q.db.QueryRow(ctx, upsertCompiledArtifactForFleet,
		arg.FleetName,
		arg.ReleaseRef,
		arg.ArtifactType,
		arg.Artifact,
		arg.Digest,
	)
	var i CompiledArtifact
	err := row.Scan(
		&i.ID,
		&i.FleetName,
		&i.EndpointID,
		&i.ReleaseRef,
		&i.ArtifactType,
		&i.Artifact,
		&i.Digest,
		&i.CompiledAt,
	)
	return i, err
}
