// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cron_executions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCronLastRun = `-- name: GetCronLastRun :one
SELECT endpoint_id, cron_name, crons_digest, run_id, scheduled_for, status,
       started_at, completed_at, message, updated_at
FROM cron_last_run
WHERE endpoint_id = $1 AND cron_name = $2
`

type GetCronLastRunParams struct {
	EndpointID string
	CronName   string
}

func (q *Queries) GetCronLastRun(ctx context.Context, arg GetCronLastRunParams) (CronLastRun, error) {
	row := q.db.QueryRow(ctx, getCronLastRun, arg.EndpointID, arg.CronName)
	var i CronLastRun
	err := row.Scan(
		&i.EndpointID,
		&i.CronName,
		&i.CronsDigest,
		&i.RunID,
		&i.ScheduledFor,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Message,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCronExecution = `-- name: InsertCronExecution :exec
INSERT INTO cron_executions (
    id, endpoint_id, cron_name, crons_digest, release_ref, run_id,
    scheduled_for, started_at, completed_at, status, message, details_json, reported_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
`

type InsertCronExecutionParams struct {
	ID           pgtype.UUID
	EndpointID   string
	CronName     string
	CronsDigest  string
	ReleaseRef   string
	RunID        pgtype.UUID
	ScheduledFor pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
	Status       string
	Message      string
	DetailsJson  []byte
}

func (q *Queries) InsertCronExecution(ctx context.Context, arg InsertCronExecutionParams) error {
	_, err := q.db.Exec(ctx, insertCronExecution,
		arg.ID,
		arg.EndpointID,
		arg.CronName,
		arg.CronsDigest,
		arg.ReleaseRef,
		arg.RunID,
		arg.ScheduledFor,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Status,
		arg.Message,
		arg.DetailsJson,
	)
	return err
}

const listCronExecutionsForEndpoint = `-- name: ListCronExecutionsForEndpoint :many
SELECT id, endpoint_id, cron_name, crons_digest, release_ref, run_id,
       scheduled_for, started_at, completed_at, status, message, details_json, reported_at
FROM cron_executions
WHERE endpoint_id = $1
ORDER BY reported_at DESC
LIMIT $2
`

type ListCronExecutionsForEndpointParams struct {
	EndpointID string
	Limit      int32
}

func (q *Queries) ListCronExecutionsForEndpoint(ctx context.Context, arg ListCronExecutionsForEndpointParams) ([]CronExecution, error) {
	rows, err := q.db.Query(ctx, listCronExecutionsForEndpoint, arg.EndpointID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronExecution{}
	for rows.Next() {
		var i CronExecution
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.CronName,
			&i.CronsDigest,
			&i.ReleaseRef,
			&i.RunID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.Message,
			&i.DetailsJson,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronLastRunsForEndpoint = `-- name: ListCronLastRunsForEndpoint :many
SELECT endpoint_id, cron_name, crons_digest, run_id, scheduled_for, status,
       started_at, completed_at, message, updated_at
FROM cron_last_run
WHERE endpoint_id = $1
ORDER BY cron_name
`

func (q *Queries) ListCronLastRunsForEndpoint(ctx context.Context, endpointID string) ([]CronLastRun, error) {
	rows, err := q.db.Query(ctx, listCronLastRunsForEndpoint, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronLastRun{}
	for rows.Next() {
		var i CronLastRun
		if err := rows.Scan(
			&i.EndpointID,
			&i.CronName,
			&i.CronsDigest,
			&i.RunID,
			&i.ScheduledFor,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Message,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCronLastRun = `-- name: UpsertCronLastRun :exec
INSERT INTO cron_last_run (
    endpoint_id, cron_name, crons_digest, run_id, scheduled_for, status,
    started_at, completed_at, message, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (endpoint_id, cron_name) DO UPDATE SET
    crons_digest = EXCLUDED.crons_digest,
    run_id = EXCLUDED.run_id,
    scheduled_for = EXCLUDED.scheduled_for,
    status = EXCLUDED.status,
    started_at = EXCLUDED.started_at,
    completed_at = EXCLUDED.completed_at,
    message = EXCLUDED.message,
    updated_at = now()
`

type UpsertCronLastRunParams struct {
	EndpointID   string
	CronName     string
	CronsDigest  string
	RunID        pgtype.UUID
	ScheduledFor pgtype.Timestamptz
	Status       string
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
	Message      string
}

func (q *Queries) UpsertCronLastRun(ctx context.Context, arg UpsertCronLastRunParams) error {
	_, err := q.db.Exec(ctx, upsertCronLastRun,
		arg.EndpointID,
		arg.CronName,
		arg.CronsDigest,
		arg.RunID,
		arg.ScheduledFor,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Message,
	)
	return err
}
