// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeploymentToken = `-- name: CreateDeploymentToken :one
INSERT INTO deployment_tokens (id, label, fleet, secret_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, label, fleet, secret_hash, expires_at, revoked_at, created_at, last_used_at
`

type CreateDeploymentTokenParams struct {
	ID         pgtype.UUID
	Label      string
	Fleet      string
	SecretHash string
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateDeploymentToken(ctx context.Context, arg CreateDeploymentTokenParams) (DeploymentToken, error) {
	row := q.db.QueryRow(ctx, createDeploymentToken,
		arg.ID,
		arg.Label,
		arg.Fleet,
		arg.SecretHash,
		arg.ExpiresAt,
	)
	var i DeploymentToken
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Fleet,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getDeploymentTokenByID = `-- name: GetDeploymentTokenByID :one
SELECT id, label, fleet, secret_hash, expires_at, revoked_at, created_at, last_used_at
FROM deployment_tokens
WHERE id = $1
`

func (q *Queries) GetDeploymentTokenByID(ctx context.Context, id pgtype.UUID) (DeploymentToken, error) {
	row := q.db.QueryRow(ctx, getDeploymentTokenByID, id)
	var i DeploymentToken
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Fleet,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getDeploymentTokenByLabel = `-- name: GetDeploymentTokenByLabel :one
SELECT id, label, fleet, secret_hash, expires_at, revoked_at, created_at, last_used_at
FROM deployment_tokens
WHERE label = $1
`

func (q *Queries) GetDeploymentTokenByLabel(ctx context.Context, label string) (DeploymentToken, error) {
	row := q.db.QueryRow(ctx, getDeploymentTokenByLabel, label)
	var i DeploymentToken
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Fleet,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listDeploymentTokens = `-- name: ListDeploymentTokens :many
SELECT id, label, fleet, expires_at, revoked_at, created_at, last_used_at
FROM deployment_tokens
ORDER BY created_at
`

type ListDeploymentTokensRow struct {
	ID         pgtype.UUID
	Label      string
	Fleet      string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) ListDeploymentTokens(ctx context.Context) ([]ListDeploymentTokensRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentTokensRow{}
	for rows.Next() {
		var i ListDeploymentTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Fleet,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDeploymentToken = `-- name: RevokeDeploymentToken :execrows
UPDATE deployment_tokens
SET revoked_at = now()
WHERE label = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeDeploymentToken(ctx context.Context, label string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeploymentToken, label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDeploymentTokenUsed = `-- name: TouchDeploymentTokenUsed :exec
UPDATE deployment_tokens
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchDeploymentTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchDeploymentTokenUsed, id)
	return err
}
