// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagnostics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeDiagnosticRequest = `-- name: CompleteDiagnosticRequest :one
UPDATE diagnostic_requests
SET status = $2,
    sha256 = $3,
    size_bytes = $4,
    error_message = $5,
    completed_at = now()
WHERE id = $1
RETURNING id, endpoint_id, requested_by, status, spec_json, s3_key, sha256, size_bytes, error_message, created_at, dispatched_at, completed_at, expires_at
`

type CompleteDiagnosticRequestParams struct {
	ID           pgtype.UUID
	Status       string
	Sha256       string
	SizeBytes    int64
	ErrorMessage string
}

func (q *Queries) CompleteDiagnosticRequest(ctx context.Context, arg CompleteDiagnosticRequestParams) (DiagnosticRequest, error) {
	row := q.db.QueryRow(ctx, completeDiagnosticRequest,
		arg.ID,
		arg.Status,
		arg.Sha256,
		arg.SizeBytes,
		arg.ErrorMessage,
	)
	var i DiagnosticRequest
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestedBy,
		&i.Status,
		&i.SpecJson,
		&i.S3Key,
		&i.Sha256,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredDiagnosticRequests = `-- name: DeleteExpiredDiagnosticRequests :many
DELETE FROM diagnostic_requests
WHERE expires_at < now()
  AND status IN ('ready', 'failed', 'expired')
RETURNING id, endpoint_id, requested_by, status, spec_json, s3_key, sha256, size_bytes, error_message, created_at, dispatched_at, completed_at, expires_at
`

func (q *Queries) DeleteExpiredDiagnosticRequests(ctx context.Context) ([]DiagnosticRequest, error) {
	rows, err := q.db.Query(ctx, deleteExpiredDiagnosticRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiagnosticRequest{}
	for rows.Next() {
		var i DiagnosticRequest
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.RequestedBy,
			&i.Status,
			&i.SpecJson,
			&i.S3Key,
			&i.Sha256,
			&i.SizeBytes,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireDiagnosticRequests = `-- name: ExpireDiagnosticRequests :exec
UPDATE diagnostic_requests
SET status = 'expired',
    completed_at = COALESCE(completed_at, now())
WHERE expires_at < now()
  AND status NOT IN ('expired')
`

func (q *Queries) ExpireDiagnosticRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireDiagnosticRequests)
	return err
}

const getActiveDiagnosticRequestForEndpoint = `-- name: GetActiveDiagnosticRequestForEndpoint :one
SELECT id, endpoint_id, requested_by, status, spec_json, s3_key, sha256, size_bytes, error_message, created_at, dispatched_at, completed_at, expires_at FROM diagnostic_requests
WHERE endpoint_id = $1
  AND status IN ('pending', 'dispatched', 'running')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveDiagnosticRequestForEndpoint(ctx context.Context, endpointID string) (DiagnosticRequest, error) {
	row := q.db.QueryRow(ctx, getActiveDiagnosticRequestForEndpoint, endpointID)
	var i DiagnosticRequest
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestedBy,
		&i.Status,
		&i.SpecJson,
		&i.S3Key,
		&i.Sha256,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getDiagnosticRequest = `-- name: GetDiagnosticRequest :one
SELECT id, endpoint_id, requested_by, status, spec_json, s3_key, sha256, size_bytes, error_message, created_at, dispatched_at, completed_at, expires_at FROM diagnostic_requests WHERE id = $1
`

func (q *Queries) GetDiagnosticRequest(ctx context.Context, id pgtype.UUID) (DiagnosticRequest, error) {
	row := q.db.QueryRow(ctx, getDiagnosticRequest, id)
	var i DiagnosticRequest
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestedBy,
		&i.Status,
		&i.SpecJson,
		&i.S3Key,
		&i.Sha256,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertDiagnosticRequest = `-- name: InsertDiagnosticRequest :one
INSERT INTO diagnostic_requests (
    id, endpoint_id, requested_by, status, spec_json, s3_key, expires_at
) VALUES (
    $1, $2, $3, 'pending', $4, $5, $6
)
RETURNING id, endpoint_id, requested_by, status, spec_json, s3_key, sha256, size_bytes, error_message, created_at, dispatched_at, completed_at, expires_at
`

type InsertDiagnosticRequestParams struct {
	ID          pgtype.UUID
	EndpointID  string
	RequestedBy string
	SpecJson    []byte
	S3Key       string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertDiagnosticRequest(ctx context.Context, arg InsertDiagnosticRequestParams) (DiagnosticRequest, error) {
	row := q.db.QueryRow(ctx, insertDiagnosticRequest,
		arg.ID,
		arg.EndpointID,
		arg.RequestedBy,
		arg.SpecJson,
		arg.S3Key,
		arg.ExpiresAt,
	)
	var i DiagnosticRequest
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestedBy,
		&i.Status,
		&i.SpecJson,
		&i.S3Key,
		&i.Sha256,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markDiagnosticRequestDispatched = `-- name: MarkDiagnosticRequestDispatched :one
UPDATE diagnostic_requests
SET status = 'dispatched',
    dispatched_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, endpoint_id, requested_by, status, spec_json, s3_key, sha256, size_bytes, error_message, created_at, dispatched_at, completed_at, expires_at
`

func (q *Queries) MarkDiagnosticRequestDispatched(ctx context.Context, id pgtype.UUID) (DiagnosticRequest, error) {
	row := q.db.QueryRow(ctx, markDiagnosticRequestDispatched, id)
	var i DiagnosticRequest
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestedBy,
		&i.Status,
		&i.SpecJson,
		&i.S3Key,
		&i.Sha256,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markDiagnosticRequestRunning = `-- name: MarkDiagnosticRequestRunning :one
UPDATE diagnostic_requests
SET status = 'running'
WHERE id = $1
  AND status IN ('pending', 'dispatched')
RETURNING id, endpoint_id, requested_by, status, spec_json, s3_key, sha256, size_bytes, error_message, created_at, dispatched_at, completed_at, expires_at
`

func (q *Queries) MarkDiagnosticRequestRunning(ctx context.Context, id pgtype.UUID) (DiagnosticRequest, error) {
	row := q.db.QueryRow(ctx, markDiagnosticRequestRunning, id)
	var i DiagnosticRequest
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestedBy,
		&i.Status,
		&i.SpecJson,
		&i.S3Key,
		&i.Sha256,
		&i.SizeBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}
