// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drift_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestDriftReport = `-- name: GetLatestDriftReport :one
SELECT id, endpoint_id, release_ref, digest, report_json, reported_at
FROM drift_reports
WHERE endpoint_id = $1
ORDER BY reported_at DESC
LIMIT 1
`

func (q *Queries) GetLatestDriftReport(ctx context.Context, endpointID string) (DriftReport, error) {
	row := q.db.QueryRow(ctx, getLatestDriftReport, endpointID)
	var i DriftReport
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.ReleaseRef,
		&i.Digest,
		&i.ReportJson,
		&i.ReportedAt,
	)
	return i, err
}

const insertDriftReport = `-- name: InsertDriftReport :exec
INSERT INTO drift_reports (id, endpoint_id, release_ref, digest, report_json, reported_at)
VALUES ($1, $2, $3, $4, $5, now())
`

type InsertDriftReportParams struct {
	ID         pgtype.UUID
	EndpointID string
	ReleaseRef string
	Digest     string
	ReportJson []byte
}

func (q *Queries) InsertDriftReport(ctx context.Context, arg InsertDriftReportParams) error {
	_, err := q.db.Exec(ctx, insertDriftReport,
		arg.ID,
		arg.EndpointID,
		arg.ReleaseRef,
		arg.Digest,
		arg.ReportJson,
	)
	return err
}
