// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint_capability_documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndpointCapabilityDocument = `-- name: GetEndpointCapabilityDocument :one
SELECT endpoint_id, digest, canonical_document, received_at FROM endpoint_capability_documents
WHERE endpoint_id = $1
`

func (q *Queries) GetEndpointCapabilityDocument(ctx context.Context, endpointID string) (EndpointCapabilityDocument, error) {
	row := q.db.QueryRow(ctx, getEndpointCapabilityDocument, endpointID)
	var document EndpointCapabilityDocument
	err := row.Scan(&document.EndpointID, &document.Digest, &document.CanonicalDocument, &document.ReceivedAt)
	return document, err
}

const upsertEndpointCapabilityDocument = `-- name: UpsertEndpointCapabilityDocument :one
INSERT INTO endpoint_capability_documents (endpoint_id, digest, canonical_document, received_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint_id) DO UPDATE
SET digest = EXCLUDED.digest,
    canonical_document = EXCLUDED.canonical_document,
    received_at = EXCLUDED.received_at
WHERE endpoint_capability_documents.digest IS DISTINCT FROM EXCLUDED.digest
RETURNING endpoint_id, digest, canonical_document, received_at
`

type UpsertEndpointCapabilityDocumentParams struct {
	EndpointID        string
	Digest            string
	CanonicalDocument []byte
	ReceivedAt        pgtype.Timestamptz
}

func (q *Queries) UpsertEndpointCapabilityDocument(ctx context.Context, arg UpsertEndpointCapabilityDocumentParams) (EndpointCapabilityDocument, error) {
	row := q.db.QueryRow(ctx, upsertEndpointCapabilityDocument, arg.EndpointID, arg.Digest, arg.CanonicalDocument, arg.ReceivedAt)
	var document EndpointCapabilityDocument
	err := row.Scan(&document.EndpointID, &document.Digest, &document.CanonicalDocument, &document.ReceivedAt)
	return document, err
}
