// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint_labels.sql

package db

import (
	"context"
)

const listEndpointLabels = `-- name: ListEndpointLabels :many
SELECT endpoint_id, key, value
FROM endpoint_labels
ORDER BY endpoint_id, key
`

type ListEndpointLabelsRow struct {
	EndpointID string
	Key        string
	Value      string
}

func (q *Queries) ListEndpointLabels(ctx context.Context) ([]ListEndpointLabelsRow, error) {
	rows, err := q.db.Query(ctx, listEndpointLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEndpointLabelsRow{}
	for rows.Next() {
		var i ListEndpointLabelsRow
		if err := rows.Scan(&i.EndpointID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointLabelsForEndpoint = `-- name: ListEndpointLabelsForEndpoint :many
SELECT key, value
FROM endpoint_labels
WHERE endpoint_id = $1
ORDER BY key
`

type ListEndpointLabelsForEndpointRow struct {
	Key   string
	Value string
}

func (q *Queries) ListEndpointLabelsForEndpoint(ctx context.Context, endpointID string) ([]ListEndpointLabelsForEndpointRow, error) {
	rows, err := q.db.Query(ctx, listEndpointLabelsForEndpoint, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEndpointLabelsForEndpointRow{}
	for rows.Next() {
		var i ListEndpointLabelsForEndpointRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEndpointLabel = `-- name: UpsertEndpointLabel :exec
INSERT INTO endpoint_labels (endpoint_id, key, value, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (endpoint_id, key) DO UPDATE
    SET value = EXCLUDED.value,
        updated_at = now()
`

type UpsertEndpointLabelParams struct {
	EndpointID string
	Key        string
	Value      string
}

func (q *Queries) UpsertEndpointLabel(ctx context.Context, arg UpsertEndpointLabelParams) error {
	_, err := q.db.Exec(ctx, upsertEndpointLabel, arg.EndpointID, arg.Key, arg.Value)
	return err
}
