// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint_delivery_states.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndpointDeliveryState = `-- name: GetEndpointDeliveryState :one
SELECT endpoint_id, target_release_ref, offered_release_ref, offered_digest, offered_schema_version, offered_at, active_release_ref, active_digest, active_schema_version, active_at, capability_blocked_target_ref, missing_requirements, unmanaged, updated_at
FROM endpoint_delivery_states WHERE endpoint_id = $1
`

func (q *Queries) GetEndpointDeliveryState(ctx context.Context, endpointID string) (EndpointDeliveryState, error) {
	row := q.db.QueryRow(ctx, getEndpointDeliveryState, endpointID)
	return scanEndpointDeliveryState(row)
}

const upsertEndpointDeliveryState = `-- name: UpsertEndpointDeliveryState :one
INSERT INTO endpoint_delivery_states (
    endpoint_id, target_release_ref,
    offered_release_ref, offered_digest, offered_schema_version, offered_at,
    active_release_ref, active_digest, active_schema_version, active_at,
    capability_blocked_target_ref, missing_requirements, unmanaged, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW()
)
ON CONFLICT (endpoint_id) DO UPDATE SET
    target_release_ref = EXCLUDED.target_release_ref,
    offered_release_ref = EXCLUDED.offered_release_ref,
    offered_digest = EXCLUDED.offered_digest,
    offered_schema_version = EXCLUDED.offered_schema_version,
    offered_at = EXCLUDED.offered_at,
    active_release_ref = EXCLUDED.active_release_ref,
    active_digest = EXCLUDED.active_digest,
    active_schema_version = EXCLUDED.active_schema_version,
    active_at = EXCLUDED.active_at,
    capability_blocked_target_ref = EXCLUDED.capability_blocked_target_ref,
    missing_requirements = EXCLUDED.missing_requirements,
    unmanaged = EXCLUDED.unmanaged,
    updated_at = NOW()
RETURNING endpoint_id, target_release_ref, offered_release_ref, offered_digest, offered_schema_version, offered_at, active_release_ref, active_digest, active_schema_version, active_at, capability_blocked_target_ref, missing_requirements, unmanaged, updated_at
`

type UpsertEndpointDeliveryStateParams struct {
	EndpointID                 string
	TargetReleaseRef           string
	OfferedReleaseRef          string
	OfferedDigest              string
	OfferedSchemaVersion       int32
	OfferedAt                  pgtype.Timestamptz
	ActiveReleaseRef           string
	ActiveDigest               string
	ActiveSchemaVersion        int32
	ActiveAt                   pgtype.Timestamptz
	CapabilityBlockedTargetRef string
	MissingRequirements        []byte
	Unmanaged                  bool
}

func (q *Queries) UpsertEndpointDeliveryState(ctx context.Context, arg UpsertEndpointDeliveryStateParams) (EndpointDeliveryState, error) {
	row := q.db.QueryRow(ctx, upsertEndpointDeliveryState,
		arg.EndpointID, arg.TargetReleaseRef,
		arg.OfferedReleaseRef, arg.OfferedDigest, arg.OfferedSchemaVersion, arg.OfferedAt,
		arg.ActiveReleaseRef, arg.ActiveDigest, arg.ActiveSchemaVersion, arg.ActiveAt,
		arg.CapabilityBlockedTargetRef, arg.MissingRequirements, arg.Unmanaged,
	)
	return scanEndpointDeliveryState(row)
}

type endpointDeliveryStateScanner interface {
	Scan(dest ...any) error
}

func scanEndpointDeliveryState(row endpointDeliveryStateScanner) (EndpointDeliveryState, error) {
	var state EndpointDeliveryState
	err := row.Scan(
		&state.EndpointID, &state.TargetReleaseRef,
		&state.OfferedReleaseRef, &state.OfferedDigest, &state.OfferedSchemaVersion, &state.OfferedAt,
		&state.ActiveReleaseRef, &state.ActiveDigest, &state.ActiveSchemaVersion, &state.ActiveAt,
		&state.CapabilityBlockedTargetRef, &state.MissingRequirements, &state.Unmanaged, &state.UpdatedAt,
	)
	return state, err
}
