// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindFingerprint = `-- name: BindFingerprint :one
UPDATE endpoints
SET cert_fingerprint = $2, updated_at = now()
WHERE id = $1
RETURNING id, fleet, cert_fingerprint, created_at, updated_at
`

type BindFingerprintParams struct {
	ID              string
	CertFingerprint pgtype.Text
}

func (q *Queries) BindFingerprint(ctx context.Context, arg BindFingerprintParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, bindFingerprint, arg.ID, arg.CertFingerprint)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Fleet,
		&i.CertFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByFingerprint = `-- name: GetEndpointByFingerprint :one
SELECT id, fleet, cert_fingerprint, created_at, updated_at FROM endpoints
WHERE cert_fingerprint = $1
`

func (q *Queries) GetEndpointByFingerprint(ctx context.Context, certFingerprint pgtype.Text) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByFingerprint, certFingerprint)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Fleet,
		&i.CertFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, fleet, cert_fingerprint, created_at, updated_at FROM endpoints
WHERE id = $1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Fleet,
		&i.CertFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, fleet, cert_fingerprint, created_at, updated_at FROM endpoints
ORDER BY created_at
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Fleet,
			&i.CertFingerprint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerEndpoint = `-- name: RegisterEndpoint :one
INSERT INTO endpoints (id, fleet, cert_fingerprint)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
    SET fleet = EXCLUDED.fleet,
        cert_fingerprint = COALESCE(EXCLUDED.cert_fingerprint, endpoints.cert_fingerprint),
        updated_at = now()
RETURNING id, fleet, cert_fingerprint, created_at, updated_at
`

type RegisterEndpointParams struct {
	ID              string
	Fleet           string
	CertFingerprint pgtype.Text
}

func (q *Queries) RegisterEndpoint(ctx context.Context, arg RegisterEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, registerEndpoint, arg.ID, arg.Fleet, arg.CertFingerprint)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Fleet,
		&i.CertFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
