// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint_system_info.sql

package db

import (
	"context"
)

const getEndpointSystemInfo = `-- name: GetEndpointSystemInfo :one
SELECT endpoint_id, digest, info_json, reported_at
FROM endpoint_system_info
WHERE endpoint_id = $1
`

func (q *Queries) GetEndpointSystemInfo(ctx context.Context, endpointID string) (EndpointSystemInfo, error) {
	row := q.db.QueryRow(ctx, getEndpointSystemInfo, endpointID)
	var i EndpointSystemInfo
	err := row.Scan(
		&i.EndpointID,
		&i.Digest,
		&i.InfoJson,
		&i.ReportedAt,
	)
	return i, err
}

const upsertEndpointSystemInfo = `-- name: UpsertEndpointSystemInfo :exec
INSERT INTO endpoint_system_info (endpoint_id, digest, info_json, reported_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (endpoint_id) DO UPDATE
SET digest = EXCLUDED.digest,
    info_json = EXCLUDED.info_json,
    reported_at = now()
`

type UpsertEndpointSystemInfoParams struct {
	EndpointID string
	Digest     string
	InfoJson   []byte
}

func (q *Queries) UpsertEndpointSystemInfo(ctx context.Context, arg UpsertEndpointSystemInfoParams) error {
	_, err := q.db.Exec(ctx, upsertEndpointSystemInfo, arg.EndpointID, arg.Digest, arg.InfoJson)
	return err
}
