// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint_system_info.sql

package db

import (
	"context"
)

const getEndpointSystemInfo = `-- name: GetEndpointSystemInfo :one
SELECT endpoint_id, digest, info_json, reported_at
FROM endpoint_system_info
WHERE endpoint_id = $1
`

func (q *Queries) GetEndpointSystemInfo(ctx context.Context, endpointID string) (EndpointSystemInfo, error) {
	row := q.db.QueryRow(ctx, getEndpointSystemInfo, endpointID)
	var i EndpointSystemInfo
	err := row.Scan(
		&i.EndpointID,
		&i.Digest,
		&i.InfoJson,
		&i.ReportedAt,
	)
	return i, err
}

const upsertEndpointSystemInfo = `-- name: UpsertEndpointSystemInfo :one
INSERT INTO endpoint_system_info (endpoint_id, digest, info_json, reported_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (endpoint_id) DO UPDATE
SET digest = EXCLUDED.digest,
    info_json = EXCLUDED.info_json,
    reported_at = now()
WHERE endpoint_system_info.digest IS DISTINCT FROM EXCLUDED.digest
   OR endpoint_system_info.info_json IS DISTINCT FROM EXCLUDED.info_json
RETURNING endpoint_id, digest, info_json, reported_at
`

type UpsertEndpointSystemInfoParams struct {
	EndpointID string
	Digest     string
	InfoJson   []byte
}

func (q *Queries) UpsertEndpointSystemInfo(ctx context.Context, arg UpsertEndpointSystemInfoParams) (EndpointSystemInfo, error) {
	row := q.db.QueryRow(ctx, upsertEndpointSystemInfo, arg.EndpointID, arg.Digest, arg.InfoJson)
	var info EndpointSystemInfo
	err := row.Scan(&info.EndpointID, &info.Digest, &info.InfoJson, &info.ReportedAt)
	return info, err
}
