// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :one
UPDATE enrollment_tokens
SET consumed_at = now()
WHERE token = $1
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING token, fleet, expires_at, consumed_at, revoked_at, created_at
`

func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, token string) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, consumeEnrollmentToken, token)
	var i EnrollmentToken
	err := row.Scan(
		&i.Token,
		&i.Fleet,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEnrollmentToken = `-- name: CreateEnrollmentToken :one
INSERT INTO enrollment_tokens (token, fleet, expires_at)
VALUES ($1, $2, $3)
RETURNING token, fleet, expires_at, consumed_at, revoked_at, created_at
`

type CreateEnrollmentTokenParams struct {
	Token     string
	Fleet     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEnrollmentToken(ctx context.Context, arg CreateEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createEnrollmentToken, arg.Token, arg.Fleet, arg.ExpiresAt)
	var i EnrollmentToken
	err := row.Scan(
		&i.Token,
		&i.Fleet,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEnrollmentTokens = `-- name: ListEnrollmentTokens :many
SELECT token, fleet, expires_at, consumed_at, revoked_at, created_at FROM enrollment_tokens
WHERE consumed_at IS NULL
  AND revoked_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListEnrollmentTokens(ctx context.Context) ([]EnrollmentToken, error) {
	rows, err := q.db.Query(ctx, listEnrollmentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentToken{}
	for rows.Next() {
		var i EnrollmentToken
		if err := rows.Scan(
			&i.Token,
			&i.Fleet,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeEnrollmentToken = `-- name: RevokeEnrollmentToken :execrows
UPDATE enrollment_tokens
SET revoked_at = now()
WHERE token = $1
  AND revoked_at IS NULL
  AND consumed_at IS NULL
`

func (q *Queries) RevokeEnrollmentToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeEnrollmentToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
