// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: firewall_audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestFirewallAuditReport = `-- name: GetLatestFirewallAuditReport :one
SELECT id, endpoint_id, digest, report_json, reported_at
FROM firewall_audit_reports
WHERE endpoint_id = $1
ORDER BY reported_at DESC
LIMIT 1
`

func (q *Queries) GetLatestFirewallAuditReport(ctx context.Context, endpointID string) (FirewallAuditReport, error) {
	row := q.db.QueryRow(ctx, getLatestFirewallAuditReport, endpointID)
	var i FirewallAuditReport
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Digest,
		&i.ReportJson,
		&i.ReportedAt,
	)
	return i, err
}

const insertFirewallAuditReport = `-- name: InsertFirewallAuditReport :exec
INSERT INTO firewall_audit_reports (id, endpoint_id, digest, report_json, reported_at)
VALUES (gen_random_uuid(), $1, $2, $3, now())
`

type InsertFirewallAuditReportParams struct {
	EndpointID string
	Digest     pgtype.Text
	ReportJson []byte
}

func (q *Queries) InsertFirewallAuditReport(ctx context.Context, arg InsertFirewallAuditReportParams) error {
	_, err := q.db.Exec(ctx, insertFirewallAuditReport, arg.EndpointID, arg.Digest, arg.ReportJson)
	return err
}

const listFleetFirewallAuditReports = `-- name: ListFleetFirewallAuditReports :many
SELECT id, endpoint_id, digest, report_json, reported_at
FROM firewall_audit_reports
WHERE endpoint_id IN (SELECT id FROM endpoints WHERE fleet = $1)
ORDER BY reported_at DESC
`

func (q *Queries) ListFleetFirewallAuditReports(ctx context.Context, fleet string) ([]FirewallAuditReport, error) {
	rows, err := q.db.Query(ctx, listFleetFirewallAuditReports, fleet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirewallAuditReport{}
	for rows.Next() {
		var i FirewallAuditReport
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.Digest,
			&i.ReportJson,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOldFirewallAuditReports = `-- name: PruneOldFirewallAuditReports :exec
DELETE FROM firewall_audit_reports
WHERE reported_at < $1
`

func (q *Queries) PruneOldFirewallAuditReports(ctx context.Context, reportedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, pruneOldFirewallAuditReports, reportedAt)
	return err
}
