// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleet_settings.sql

package db

import (
	"context"
)

const ensureFleet = `-- name: EnsureFleet :exec
INSERT INTO fleet_settings (fleet, remediation_policy)
VALUES ($1, 'auto')
ON CONFLICT (fleet) DO NOTHING
`

func (q *Queries) EnsureFleet(ctx context.Context, fleet string) error {
	_, err := q.db.Exec(ctx, ensureFleet, fleet)
	return err
}

const getFleetSettings = `-- name: GetFleetSettings :one
SELECT fleet, remediation_policy, created_at, updated_at FROM fleet_settings
WHERE fleet = $1
`

func (q *Queries) GetFleetSettings(ctx context.Context, fleet string) (FleetSetting, error) {
	row := q.db.QueryRow(ctx, getFleetSettings, fleet)
	var i FleetSetting
	err := row.Scan(
		&i.Fleet,
		&i.RemediationPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFleets = `-- name: ListFleets :many
SELECT fleet, remediation_policy, created_at, updated_at FROM fleet_settings
ORDER BY fleet
`

func (q *Queries) ListFleets(ctx context.Context) ([]FleetSetting, error) {
	rows, err := q.db.Query(ctx, listFleets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetSetting{}
	for rows.Next() {
		var i FleetSetting
		if err := rows.Scan(
			&i.Fleet,
			&i.RemediationPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFleetSettings = `-- name: UpsertFleetSettings :one
INSERT INTO fleet_settings (fleet, remediation_policy)
VALUES ($1, $2)
ON CONFLICT (fleet) DO UPDATE
    SET remediation_policy = EXCLUDED.remediation_policy,
        updated_at = now()
RETURNING fleet, remediation_policy, created_at, updated_at
`

type UpsertFleetSettingsParams struct {
	Fleet             string
	RemediationPolicy string
}

func (q *Queries) UpsertFleetSettings(ctx context.Context, arg UpsertFleetSettingsParams) (FleetSetting, error) {
	row := q.db.QueryRow(ctx, upsertFleetSettings, arg.Fleet, arg.RemediationPolicy)
	var i FleetSetting
	err := row.Scan(
		&i.Fleet,
		&i.RemediationPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
