// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApplyFailure struct {
	ID              pgtype.UUID
	EndpointID      pgtype.UUID
	ReleaseRef      string
	ResourceAddress string
	Message         string
	ReportedAt      pgtype.Timestamptz
}

type DeploymentToken struct {
	ID         pgtype.UUID
	Label      string
	Fleet      string
	SecretHash string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type DriftReport struct {
	ID         pgtype.UUID
	EndpointID pgtype.UUID
	ReleaseRef string
	Digest     string
	ReportJson []byte
	ReportedAt pgtype.Timestamptz
}

type Endpoint struct {
	ID              pgtype.UUID
	Fleet           string
	CertFingerprint pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type EndpointLabel struct {
	EndpointID pgtype.UUID
	Key        string
	Value      string
	UpdatedAt  pgtype.Timestamptz
}

type EnrollmentToken struct {
	Token      string
	Fleet      string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type FleetSetting struct {
	Fleet             string
	RemediationPolicy string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type OperatorCredential struct {
	CertFingerprint string
	CreatedAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type ServerSetting struct {
	Key   string
	Value string
}
