// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator_credentials.sql

package db

import (
	"context"
)

const countOperatorCredentials = `-- name: CountOperatorCredentials :one
SELECT count(*)::bigint AS count FROM operator_credentials
WHERE revoked_at IS NULL
`

func (q *Queries) CountOperatorCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOperatorCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isOperatorCredential = `-- name: IsOperatorCredential :one
SELECT cert_fingerprint FROM operator_credentials
WHERE cert_fingerprint = $1
  AND revoked_at IS NULL
`

func (q *Queries) IsOperatorCredential(ctx context.Context, certFingerprint string) (string, error) {
	row := q.db.QueryRow(ctx, isOperatorCredential, certFingerprint)
	var cert_fingerprint string
	err := row.Scan(&cert_fingerprint)
	return cert_fingerprint, err
}

const listOperatorCredentials = `-- name: ListOperatorCredentials :many
SELECT cert_fingerprint, created_at, revoked_at FROM operator_credentials
WHERE revoked_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListOperatorCredentials(ctx context.Context) ([]OperatorCredential, error) {
	rows, err := q.db.Query(ctx, listOperatorCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorCredential{}
	for rows.Next() {
		var i OperatorCredential
		if err := rows.Scan(&i.CertFingerprint, &i.CreatedAt, &i.RevokedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerOperatorCredential = `-- name: RegisterOperatorCredential :one
INSERT INTO operator_credentials (cert_fingerprint)
VALUES ($1)
ON CONFLICT (cert_fingerprint) DO UPDATE
    SET revoked_at = NULL
RETURNING cert_fingerprint, created_at, revoked_at
`

func (q *Queries) RegisterOperatorCredential(ctx context.Context, certFingerprint string) (OperatorCredential, error) {
	row := q.db.QueryRow(ctx, registerOperatorCredential, certFingerprint)
	var i OperatorCredential
	err := row.Scan(&i.CertFingerprint, &i.CreatedAt, &i.RevokedAt)
	return i, err
}
