// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRBACRole = `-- name: DeleteRBACRole :execrows
DELETE FROM rbac_roles
WHERE name = $1 AND built_in = false
`

func (q *Queries) DeleteRBACRole(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRBACRole, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRBACRule = `-- name: DeleteRBACRule :execrows
DELETE FROM rbac_rules
WHERE id = $1 AND role_name = $2
`

type DeleteRBACRuleParams struct {
	ID       pgtype.UUID
	RoleName string
}

func (q *Queries) DeleteRBACRule(ctx context.Context, arg DeleteRBACRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRBACRule, arg.ID, arg.RoleName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRBACRole = `-- name: GetRBACRole :one
SELECT name, description, built_in, created_at
FROM rbac_roles
WHERE name = $1
`

func (q *Queries) GetRBACRole(ctx context.Context, name string) (RbacRole, error) {
	row := q.db.QueryRow(ctx, getRBACRole, name)
	var i RbacRole
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.BuiltIn,
		&i.CreatedAt,
	)
	return i, err
}

const insertOperatorRoleAssignment = `-- name: InsertOperatorRoleAssignment :exec
INSERT INTO operator_role_assignments (operator_id, role_name)
VALUES ($1, $2)
`

type InsertOperatorRoleAssignmentParams struct {
	OperatorID string
	RoleName   string
}

func (q *Queries) InsertOperatorRoleAssignment(ctx context.Context, arg InsertOperatorRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertOperatorRoleAssignment, arg.OperatorID, arg.RoleName)
	return err
}

const insertRBACRule = `-- name: InsertRBACRule :one
INSERT INTO rbac_rules (id, role_name, method, path_pattern)
VALUES ($1, $2, $3, $4)
RETURNING id, role_name, method, path_pattern, created_at
`

type InsertRBACRuleParams struct {
	ID          pgtype.UUID
	RoleName    string
	Method      string
	PathPattern string
}

func (q *Queries) InsertRBACRule(ctx context.Context, arg InsertRBACRuleParams) (RbacRule, error) {
	row := q.db.QueryRow(ctx, insertRBACRule,
		arg.ID,
		arg.RoleName,
		arg.Method,
		arg.PathPattern,
	)
	var i RbacRule
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.Method,
		&i.PathPattern,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveOperators = `-- name: ListActiveOperators :many
SELECT cert_fingerprint, operator_id, created_at, revoked_at
FROM operator_credentials
WHERE revoked_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListActiveOperators(ctx context.Context) ([]OperatorCredential, error) {
	rows, err := q.db.Query(ctx, listActiveOperators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorCredential{}
	for rows.Next() {
		var i OperatorCredential
		if err := rows.Scan(
			&i.CertFingerprint,
			&i.OperatorID,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorRoleAssignments = `-- name: ListOperatorRoleAssignments :many
SELECT operator_id, role_name
FROM operator_role_assignments
ORDER BY operator_id, role_name
`

func (q *Queries) ListOperatorRoleAssignments(ctx context.Context) ([]OperatorRoleAssignment, error) {
	rows, err := q.db.Query(ctx, listOperatorRoleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorRoleAssignment{}
	for rows.Next() {
		var i OperatorRoleAssignment
		if err := rows.Scan(&i.OperatorID, &i.RoleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorRoleAssignmentsForOperator = `-- name: ListOperatorRoleAssignmentsForOperator :many
SELECT role_name
FROM operator_role_assignments
WHERE operator_id = $1
ORDER BY role_name
`

func (q *Queries) ListOperatorRoleAssignmentsForOperator(ctx context.Context, operatorID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listOperatorRoleAssignmentsForOperator, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_name string
		if err := rows.Scan(&role_name); err != nil {
			return nil, err
		}
		items = append(items, role_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRBACRoles = `-- name: ListRBACRoles :many
SELECT name, description, built_in, created_at
FROM rbac_roles
ORDER BY built_in DESC, name
`

func (q *Queries) ListRBACRoles(ctx context.Context) ([]RbacRole, error) {
	rows, err := q.db.Query(ctx, listRBACRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RbacRole{}
	for rows.Next() {
		var i RbacRole
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.BuiltIn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRBACRulesForRole = `-- name: ListRBACRulesForRole :many
SELECT id, role_name, method, path_pattern, created_at
FROM rbac_rules
WHERE role_name = $1
ORDER BY created_at, id
`

func (q *Queries) ListRBACRulesForRole(ctx context.Context, roleName string) ([]RbacRule, error) {
	rows, err := q.db.Query(ctx, listRBACRulesForRole, roleName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RbacRule{}
	for rows.Next() {
		var i RbacRule
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.Method,
			&i.PathPattern,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceOperatorRoleAssignments = `-- name: ReplaceOperatorRoleAssignments :exec
DELETE FROM operator_role_assignments
WHERE operator_id = $1
`

func (q *Queries) ReplaceOperatorRoleAssignments(ctx context.Context, operatorID string) error {
	_, err := q.db.Exec(ctx, replaceOperatorRoleAssignments, operatorID)
	return err
}

const upsertRBACRole = `-- name: UpsertRBACRole :exec
INSERT INTO rbac_roles (name, description, built_in)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
    SET description = EXCLUDED.description,
        built_in = EXCLUDED.built_in
`

type UpsertRBACRoleParams struct {
	Name        string
	Description string
	BuiltIn     bool
}

func (q *Queries) UpsertRBACRole(ctx context.Context, arg UpsertRBACRoleParams) error {
	_, err := q.db.Exec(ctx, upsertRBACRole, arg.Name, arg.Description, arg.BuiltIn)
	return err
}
