// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateSecretVersion = `-- name: AllocateSecretVersion :one
INSERT INTO secret_names (name, next_version)
VALUES ($1, 2)
ON CONFLICT (name) DO UPDATE
SET next_version = secret_names.next_version + 1,
    updated_at = now()
RETURNING next_version - 1 AS version
`

func (q *Queries) AllocateSecretVersion(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, allocateSecretVersion, name)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const createSecretVersion = `-- name: CreateSecretVersion :exec
INSERT INTO secret_versions (name, version, envelope_json, created_at, created_by)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSecretVersionParams struct {
	Name         string
	Version      int64
	EnvelopeJson []byte
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
}

func (q *Queries) CreateSecretVersion(ctx context.Context, arg CreateSecretVersionParams) error {
	_, err := q.db.Exec(ctx, createSecretVersion, arg.Name, arg.Version, arg.EnvelopeJson, arg.CreatedAt, arg.CreatedBy)
	return err
}

const getExactSecretVersion = `-- name: GetExactSecretVersion :one
SELECT sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json,
       (sn.active_version = sv.version) AS active,
       CASE WHEN sn.active_version = sv.version THEN sn.activation_generation ELSE 0 END AS activation_generation
FROM secret_versions sv
JOIN secret_names sn ON sn.name = sv.name
WHERE sv.name = $1 AND sv.version = $2
`

type GetExactSecretVersionParams struct {
	Name    string
	Version int64
}

func (q *Queries) GetExactSecretVersion(ctx context.Context, arg GetExactSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, getExactSecretVersion, arg.Name, arg.Version)
	return scanSecretVersion(row)
}

const getActiveSecretVersion = `-- name: GetActiveSecretVersion :one
SELECT sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json,
       TRUE AS active, sn.activation_generation
FROM secret_versions sv
JOIN secret_names sn ON sn.name = sv.name AND sn.active_version = sv.version
WHERE sv.name = $1
`

func (q *Queries) GetActiveSecretVersion(ctx context.Context, name string) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, getActiveSecretVersion, name)
	return scanSecretVersion(row)
}

const listSecretVersions = `-- name: ListSecretVersions :many
SELECT sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json,
       (sn.active_version = sv.version) AS active,
       CASE WHEN sn.active_version = sv.version THEN sn.activation_generation ELSE 0 END AS activation_generation
FROM secret_versions sv
JOIN secret_names sn ON sn.name = sv.name
WHERE sv.name = $1
ORDER BY sv.version
`

func (q *Queries) ListSecretVersions(ctx context.Context, name string) ([]SecretVersion, error) {
	rows, err := q.db.Query(ctx, listSecretVersions, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretVersion{}
	for rows.Next() {
		item, err := scanSecretVersion(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

const getSecretActivationGeneration = `-- name: GetSecretActivationGeneration :one
SELECT activation_generation FROM secret_names WHERE name = $1
`

func (q *Queries) GetSecretActivationGeneration(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, getSecretActivationGeneration, name)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const activateSecretVersion = `-- name: ActivateSecretVersion :one
WITH candidate AS (
    SELECT 1 FROM secret_versions
    WHERE name = $1 AND version = $2 AND revoked_at IS NULL
), activated_name AS (
    UPDATE secret_names
    SET active_version = $2,
        activation_generation = activation_generation + 1,
        updated_at = now()
    WHERE name = $1
      AND activation_generation = $3 - 1
      AND EXISTS (SELECT 1 FROM candidate)
    RETURNING activation_generation
)
UPDATE secret_versions sv
SET activated_at = now(), activated_by = $4, rollouts_json = $5
FROM activated_name an
WHERE sv.name = $1 AND sv.version = $2
RETURNING sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json,
          TRUE AS active, an.activation_generation
`

type ActivateSecretVersionParams struct {
	Name                 string
	Version              int64
	ActivationGeneration int64
	ActivatedBy          string
	RolloutsJson         []byte
}

func (q *Queries) ActivateSecretVersion(ctx context.Context, arg ActivateSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, activateSecretVersion, arg.Name, arg.Version, arg.ActivationGeneration, arg.ActivatedBy, arg.RolloutsJson)
	return scanSecretVersion(row)
}

const revokeSecretVersion = `-- name: RevokeSecretVersion :one
UPDATE secret_versions sv
SET revoked_at = COALESCE(revoked_at, now()),
    revoked_by = CASE WHEN revoked_at IS NULL THEN $3 ELSE revoked_by END
WHERE name = $1 AND version = $2
RETURNING sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json,
    ((SELECT active_version FROM secret_names WHERE name = $1) = sv.version) AS active,
    CASE WHEN (SELECT active_version FROM secret_names WHERE name = $1) = sv.version
         THEN (SELECT activation_generation FROM secret_names WHERE name = $1)
         ELSE 0 END AS activation_generation
`

type RevokeSecretVersionParams struct {
	Name      string
	Version   int64
	RevokedBy string
}

func (q *Queries) RevokeSecretVersion(ctx context.Context, arg RevokeSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, revokeSecretVersion, arg.Name, arg.Version, arg.RevokedBy)
	return scanSecretVersion(row)
}

type rowScanner interface {
	Scan(...any) error
}

func scanSecretVersion(row rowScanner) (SecretVersion, error) {
	var item SecretVersion
	err := row.Scan(
		&item.Name, &item.Version, &item.EnvelopeJson, &item.CreatedAt, &item.CreatedBy,
		&item.ActivatedAt, &item.ActivatedBy, &item.RevokedAt, &item.RevokedBy, &item.RolloutsJson,
		&item.Active, &item.ActivationGeneration,
	)
	return item, err
}
