// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonSecretRollbackReferences = `-- name: AbandonSecretRollbackReferences :exec
UPDATE secret_rollback_references
SET status = 'abandoned', abandoned_at = $4, abandoned_by = $3
WHERE name = $1 AND version = $2 AND status = 'armed' AND expires_at > $4
`

type AbandonSecretRollbackReferencesParams struct {
	Name        string
	Version     int64
	AbandonedBy string
	AbandonedAt pgtype.Timestamptz
}

func (q *Queries) AbandonSecretRollbackReferences(ctx context.Context, arg AbandonSecretRollbackReferencesParams) error {
	_, err := q.db.Exec(ctx, abandonSecretRollbackReferences,
		arg.Name,
		arg.Version,
		arg.AbandonedBy,
		arg.AbandonedAt,
	)
	return err
}

const activateSecretVersion = `-- name: ActivateSecretVersion :one
WITH candidate AS (
    SELECT 1 FROM secret_versions
    WHERE name = $1 AND version = $2 AND revoked_at IS NULL
), activated_name AS (
    UPDATE secret_names
    SET active_version = $2,
        activation_generation = activation_generation + 1,
        updated_at = now()
    WHERE name = $1
      AND activation_generation = $3 - 1
      AND EXISTS (SELECT 1 FROM candidate)
    RETURNING activation_generation
)
UPDATE secret_versions sv
SET activated_at = now(), activated_by = $4, rollouts_json = $5
FROM activated_name an
WHERE sv.name = $1 AND sv.version = $2
RETURNING sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json, TRUE AS active, an.activation_generation
`

type ActivateSecretVersionParams struct {
	Name         string
	Version      int64
	Column3      interface{}
	ActivatedBy  string
	RolloutsJson []byte
}

type ActivateSecretVersionRow struct {
	Name                 string
	Version              int64
	EnvelopeJson         []byte
	CreatedAt            pgtype.Timestamptz
	CreatedBy            string
	ActivatedAt          pgtype.Timestamptz
	ActivatedBy          string
	RevokedAt            pgtype.Timestamptz
	RevokedBy            string
	RolloutsJson         []byte
	Active               bool
	ActivationGeneration int64
}

func (q *Queries) ActivateSecretVersion(ctx context.Context, arg ActivateSecretVersionParams) (ActivateSecretVersionRow, error) {
	row := q.db.QueryRow(ctx, activateSecretVersion,
		arg.Name,
		arg.Version,
		arg.Column3,
		arg.ActivatedBy,
		arg.RolloutsJson,
	)
	var i ActivateSecretVersionRow
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.EnvelopeJson,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RolloutsJson,
		&i.Active,
		&i.ActivationGeneration,
	)
	return i, err
}

const allocateSecretVersion = `-- name: AllocateSecretVersion :one
INSERT INTO secret_names (name, scope_type, scope_id, next_version)
VALUES ($1, $2, NULLIF($3, ''), 2)
ON CONFLICT (name) DO UPDATE
SET next_version = secret_names.next_version + 1,
    updated_at = now()
WHERE secret_names.scope_type = EXCLUDED.scope_type
  AND secret_names.scope_id IS NOT DISTINCT FROM EXCLUDED.scope_id
RETURNING (next_version - 1)::BIGINT AS version
`

type AllocateSecretVersionParams struct {
	Name      string
	ScopeType string
	ScopeID   string
}

func (q *Queries) AllocateSecretVersion(ctx context.Context, arg AllocateSecretVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateSecretVersion, arg.Name, arg.ScopeType, arg.ScopeID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const createSecretRollbackReference = `-- name: CreateSecretRollbackReference :exec
INSERT INTO secret_rollback_references (
    id, name, version, fingerprint, resource_address, artifact_digest,
    attempt, created_at, expires_at, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateSecretRollbackReferenceParams struct {
	ID              string
	Name            string
	Version         int64
	Fingerprint     string
	ResourceAddress string
	ArtifactDigest  string
	Attempt         int64
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	Status          string
}

func (q *Queries) CreateSecretRollbackReference(ctx context.Context, arg CreateSecretRollbackReferenceParams) error {
	_, err := q.db.Exec(ctx, createSecretRollbackReference,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Fingerprint,
		arg.ResourceAddress,
		arg.ArtifactDigest,
		arg.Attempt,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Status,
	)
	return err
}

const createSecretVersion = `-- name: CreateSecretVersion :exec
INSERT INTO secret_versions (name, version, envelope_json, created_at, created_by)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSecretVersionParams struct {
	Name         string
	Version      int64
	EnvelopeJson []byte
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
}

func (q *Queries) CreateSecretVersion(ctx context.Context, arg CreateSecretVersionParams) error {
	_, err := q.db.Exec(ctx, createSecretVersion,
		arg.Name,
		arg.Version,
		arg.EnvelopeJson,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const deleteSecretVersion = `-- name: DeleteSecretVersion :one
DELETE FROM secret_versions sv
WHERE sv.name = $1 AND sv.version = $2
  AND NOT EXISTS (
      SELECT 1 FROM secret_names sn
      WHERE sn.name = sv.name AND sn.active_version = sv.version
  )
  AND NOT EXISTS (
      SELECT 1 FROM secret_rollback_references rr
      WHERE rr.name = sv.name AND rr.version = sv.version
        AND rr.status = 'armed' AND rr.expires_at > $3
  )
RETURNING sv.version
`

type DeleteSecretVersionParams struct {
	Name    string
	Version int64
	Now     pgtype.Timestamptz
}

func (q *Queries) DeleteSecretVersion(ctx context.Context, arg DeleteSecretVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSecretVersion, arg.Name, arg.Version, arg.Now)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getActiveSecretVersion = `-- name: GetActiveSecretVersion :one
SELECT sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json, TRUE AS active, sn.activation_generation
FROM secret_versions sv
JOIN secret_names sn ON sn.name = sv.name AND sn.active_version = sv.version
WHERE sv.name = $1
`

type GetActiveSecretVersionRow struct {
	Name                 string
	Version              int64
	EnvelopeJson         []byte
	CreatedAt            pgtype.Timestamptz
	CreatedBy            string
	ActivatedAt          pgtype.Timestamptz
	ActivatedBy          string
	RevokedAt            pgtype.Timestamptz
	RevokedBy            string
	RolloutsJson         []byte
	Active               bool
	ActivationGeneration int64
}

func (q *Queries) GetActiveSecretVersion(ctx context.Context, name string) (GetActiveSecretVersionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSecretVersion, name)
	var i GetActiveSecretVersionRow
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.EnvelopeJson,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RolloutsJson,
		&i.Active,
		&i.ActivationGeneration,
	)
	return i, err
}

const getExactSecretVersion = `-- name: GetExactSecretVersion :one
SELECT sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json, CASE WHEN sn.active_version = sv.version THEN TRUE ELSE FALSE END AS active,
       CASE WHEN sn.active_version = sv.version THEN sn.activation_generation ELSE 0::BIGINT END AS activation_generation
FROM secret_versions sv
JOIN secret_names sn ON sn.name = sv.name
WHERE sv.name = $1 AND sv.version = $2
`

type GetExactSecretVersionParams struct {
	Name    string
	Version int64
}

type GetExactSecretVersionRow struct {
	Name                 string
	Version              int64
	EnvelopeJson         []byte
	CreatedAt            pgtype.Timestamptz
	CreatedBy            string
	ActivatedAt          pgtype.Timestamptz
	ActivatedBy          string
	RevokedAt            pgtype.Timestamptz
	RevokedBy            string
	RolloutsJson         []byte
	Active               bool
	ActivationGeneration int64
}

func (q *Queries) GetExactSecretVersion(ctx context.Context, arg GetExactSecretVersionParams) (GetExactSecretVersionRow, error) {
	row := q.db.QueryRow(ctx, getExactSecretVersion, arg.Name, arg.Version)
	var i GetExactSecretVersionRow
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.EnvelopeJson,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RolloutsJson,
		&i.Active,
		&i.ActivationGeneration,
	)
	return i, err
}

const getSecretActivationGeneration = `-- name: GetSecretActivationGeneration :one
SELECT activation_generation FROM secret_names WHERE name = $1
`

func (q *Queries) GetSecretActivationGeneration(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, getSecretActivationGeneration, name)
	var activation_generation int64
	err := row.Scan(&activation_generation)
	return activation_generation, err
}

const listActiveSecretRollbackReferences = `-- name: ListActiveSecretRollbackReferences :many
SELECT id, name, version, fingerprint, resource_address, artifact_digest,
       attempt, created_at, expires_at, status, abandoned_at, abandoned_by
FROM secret_rollback_references
WHERE name = $1 AND version = $2 AND status = 'armed' AND expires_at > $3
ORDER BY id
`

type ListActiveSecretRollbackReferencesParams struct {
	Name    string
	Version int64
	Now     pgtype.Timestamptz
}

func (q *Queries) ListActiveSecretRollbackReferences(ctx context.Context, arg ListActiveSecretRollbackReferencesParams) ([]SecretRollbackReference, error) {
	rows, err := q.db.Query(ctx, listActiveSecretRollbackReferences, arg.Name, arg.Version, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretRollbackReference{}
	for rows.Next() {
		var i SecretRollbackReference
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Fingerprint,
			&i.ResourceAddress,
			&i.ArtifactDigest,
			&i.Attempt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.AbandonedAt,
			&i.AbandonedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretVersions = `-- name: ListSecretVersions :many
SELECT sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json, CASE WHEN sn.active_version = sv.version THEN TRUE ELSE FALSE END AS active,
       CASE WHEN sn.active_version = sv.version THEN sn.activation_generation ELSE 0::BIGINT END AS activation_generation
FROM secret_versions sv
JOIN secret_names sn ON sn.name = sv.name
WHERE sv.name = $1
ORDER BY sv.version
`

type ListSecretVersionsRow struct {
	Name                 string
	Version              int64
	EnvelopeJson         []byte
	CreatedAt            pgtype.Timestamptz
	CreatedBy            string
	ActivatedAt          pgtype.Timestamptz
	ActivatedBy          string
	RevokedAt            pgtype.Timestamptz
	RevokedBy            string
	RolloutsJson         []byte
	Active               bool
	ActivationGeneration int64
}

func (q *Queries) ListSecretVersions(ctx context.Context, name string) ([]ListSecretVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSecretVersions, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretVersionsRow{}
	for rows.Next() {
		var i ListSecretVersionsRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.EnvelopeJson,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ActivatedAt,
			&i.ActivatedBy,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RolloutsJson,
			&i.Active,
			&i.ActivationGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogicalSecrets = `-- name: ListLogicalSecrets :many
SELECT sn.name, sn.scope_type, COALESCE(sn.scope_id, '') AS scope_id,
       COALESCE(sn.active_version, 0)::BIGINT AS active_version,
       count(sv.version)::BIGINT AS version_count,
       COALESCE(active.envelope_json->>'fingerprint', '') AS fingerprint,
       min(sv.created_at) AS created_at,
       max(sv.created_at) AS updated_at
FROM secret_names sn
JOIN secret_versions sv ON sv.name = sn.name
LEFT JOIN secret_versions active ON active.name = sn.name AND active.version = sn.active_version
WHERE sn.name > $1
GROUP BY sn.name, sn.scope_type, sn.scope_id, sn.active_version, active.envelope_json
ORDER BY sn.name
LIMIT $2
`

type ListLogicalSecretsParams struct {
	Cursor   string
	PageSize int32
}

type ListLogicalSecretsRow struct {
	Name          string
	ScopeType     string
	ScopeID       string
	ActiveVersion int64
	VersionCount  int64
	Fingerprint   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListLogicalSecrets(ctx context.Context, arg ListLogicalSecretsParams) ([]ListLogicalSecretsRow, error) {
	rows, err := q.db.Query(ctx, listLogicalSecrets, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogicalSecretsRow{}
	for rows.Next() {
		var i ListLogicalSecretsRow
		if err := rows.Scan(&i.Name, &i.ScopeType, &i.ScopeID, &i.ActiveVersion, &i.VersionCount, &i.Fingerprint, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSecretVersion = `-- name: RevokeSecretVersion :one
UPDATE secret_versions sv
SET revoked_at = COALESCE(sv.revoked_at, now()),
    revoked_by = CASE WHEN sv.revoked_at IS NULL THEN $3 ELSE sv.revoked_by END
WHERE sv.name = $1 AND sv.version = $2
RETURNING sv.name, sv.version, sv.envelope_json, sv.created_at, sv.created_by, sv.activated_at, sv.activated_by, sv.revoked_at, sv.revoked_by, sv.rollouts_json,
    CASE WHEN (SELECT active_version FROM secret_names WHERE secret_names.name = $1) = sv.version
         THEN TRUE ELSE FALSE END AS active,
    CASE WHEN (SELECT active_version FROM secret_names WHERE secret_names.name = $1) = sv.version
         THEN (SELECT activation_generation FROM secret_names WHERE secret_names.name = $1)
         ELSE 0::BIGINT END AS activation_generation
`

type RevokeSecretVersionParams struct {
	Name      string
	Version   int64
	RevokedBy string
}

type RevokeSecretVersionRow struct {
	Name                 string
	Version              int64
	EnvelopeJson         []byte
	CreatedAt            pgtype.Timestamptz
	CreatedBy            string
	ActivatedAt          pgtype.Timestamptz
	ActivatedBy          string
	RevokedAt            pgtype.Timestamptz
	RevokedBy            string
	RolloutsJson         []byte
	Active               bool
	ActivationGeneration int64
}

func (q *Queries) RevokeSecretVersion(ctx context.Context, arg RevokeSecretVersionParams) (RevokeSecretVersionRow, error) {
	row := q.db.QueryRow(ctx, revokeSecretVersion, arg.Name, arg.Version, arg.RevokedBy)
	var i RevokeSecretVersionRow
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.EnvelopeJson,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RolloutsJson,
		&i.Active,
		&i.ActivationGeneration,
	)
	return i, err
}
