// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_settings.sql

package db

import (
	"context"
)

const getServerSetting = `-- name: GetServerSetting :one
SELECT value FROM server_settings
WHERE key = $1
`

func (q *Queries) GetServerSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getServerSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertServerSetting = `-- name: UpsertServerSetting :exec
INSERT INTO server_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
    SET value = EXCLUDED.value
`

type UpsertServerSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertServerSetting(ctx context.Context, arg UpsertServerSettingParams) error {
	_, err := q.db.Exec(ctx, upsertServerSetting, arg.Key, arg.Value)
	return err
}
