// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BootstrapProfile(arg1:main.ConnectionProfile,arg2:string):Promise<main.ConnectionView>;

export function ConnectProfile(arg1:main.ConnectionProfile):Promise<main.ConnectionView>;

export function GetApplicationInfo():Promise<main.ApplicationInfo>;

export function LoadEndpointDetail(arg1:string):Promise<main.EndpointDetailView>;

export function LoadFleetDetail(arg1:string):Promise<main.FleetDetailView>;

export function LoadProfiles():Promise<Array<main.ConnectionProfile>>;

export function LoadWorkspace():Promise<main.WorkspaceView>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function SaveProfile(arg1:main.ConnectionProfile):Promise<void>;
