// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BootstrapProfile(arg1, arg2) {
  return window['go']['main']['App']['BootstrapProfile'](arg1, arg2);
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function GetApplicationInfo() {
  return window['go']['main']['App']['GetApplicationInfo']();
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function OpenExternalLink(arg1) {
  return window['go']['main']['App']['OpenExternalLink'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}
