// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BootstrapProfile(arg1, arg2) {
  return window['go']['main']['App']['BootstrapProfile'](arg1, arg2);
}

export function ClearEnrollmentToken() {
  return window['go']['main']['App']['ClearEnrollmentToken']();
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function CopyEnrollmentToken() {
  return window['go']['main']['App']['CopyEnrollmentToken']();
}

export function CreateEnrollmentToken(arg1) {
  return window['go']['main']['App']['CreateEnrollmentToken'](arg1);
}

export function GetApplicationInfo() {
  return window['go']['main']['App']['GetApplicationInfo']();
}

export function GetDiagnosticCapabilities() {
  return window['go']['main']['App']['GetDiagnosticCapabilities']();
}

export function LoadActivityPage(arg1) {
  return window['go']['main']['App']['LoadActivityPage'](arg1);
}

export function LoadAssetInventory() {
  return window['go']['main']['App']['LoadAssetInventory']();
}

export function LoadAuditExportInfo() {
  return window['go']['main']['App']['LoadAuditExportInfo']();
}

export function LoadChangeRequestDetail(arg1) {
  return window['go']['main']['App']['LoadChangeRequestDetail'](arg1);
}

export function LoadDiagnosticRequest(arg1) {
  return window['go']['main']['App']['LoadDiagnosticRequest'](arg1);
}

export function LoadEndpointDetail(arg1) {
  return window['go']['main']['App']['LoadEndpointDetail'](arg1);
}

export function LoadFirewallReport(arg1) {
  return window['go']['main']['App']['LoadFirewallReport'](arg1);
}

export function LoadFleetDetail(arg1) {
  return window['go']['main']['App']['LoadFleetDetail'](arg1);
}

export function LoadFleetOperationalReports(arg1) {
  return window['go']['main']['App']['LoadFleetOperationalReports'](arg1);
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function LoadWorkspace() {
  return window['go']['main']['App']['LoadWorkspace']();
}

export function OpenExternalLink(arg1) {
  return window['go']['main']['App']['OpenExternalLink'](arg1);
}

export function RemoveEndpoint(arg1) {
  return window['go']['main']['App']['RemoveEndpoint'](arg1);
}

export function RemoveEndpointLabel(arg1) {
  return window['go']['main']['App']['RemoveEndpointLabel'](arg1);
}

export function RequestDiagnosticCollection(arg1) {
  return window['go']['main']['App']['RequestDiagnosticCollection'](arg1);
}

export function RequestEndpointAgentUpgrade(arg1) {
  return window['go']['main']['App']['RequestEndpointAgentUpgrade'](arg1);
}

export function RequestFleetAgentUpgrade(arg1) {
  return window['go']['main']['App']['RequestFleetAgentUpgrade'](arg1);
}

export function RequestGitSync() {
  return window['go']['main']['App']['RequestGitSync']();
}

export function SaveAssetInventory(arg1) {
  return window['go']['main']['App']['SaveAssetInventory'](arg1);
}

export function SaveDiagnosticBundle(arg1) {
  return window['go']['main']['App']['SaveDiagnosticBundle'](arg1);
}

export function SaveFirewallReport(arg1) {
  return window['go']['main']['App']['SaveFirewallReport'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SetEndpointLabel(arg1) {
  return window['go']['main']['App']['SetEndpointLabel'](arg1);
}
