// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BootstrapProfile(arg1:main.ConnectionProfile,arg2:string):Promise<main.ConnectionView>;

export function ClearEnrollmentToken():Promise<void>;

export function ConnectProfile(arg1:main.ConnectionProfile):Promise<main.ConnectionView>;

export function CopyEnrollmentToken():Promise<void>;

export function CreateEnrollmentToken(arg1:main.EnrollmentTokenRequest):Promise<main.EnrollmentTokenResult>;

export function GetApplicationInfo():Promise<main.ApplicationInfo>;

export function LoadActivityPage(arg1:main.ActivityPageRequest):Promise<main.ActivityPageView>;

export function LoadChangeRequestDetail(arg1:string):Promise<main.ChangeRequestDetailView>;

export function LoadEndpointDetail(arg1:string):Promise<main.EndpointDetailView>;

export function LoadFleetDetail(arg1:string):Promise<main.FleetDetailView>;

export function LoadProfiles():Promise<Array<main.ConnectionProfile>>;

export function LoadWorkspace():Promise<main.WorkspaceView>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function RemoveEndpointLabel(arg1:main.EndpointLabelRemoveRequest):Promise<main.EndpointLabelResultView>;

export function RequestEndpointAgentUpgrade(arg1:main.EndpointUpgradeRequest):Promise<main.EndpointUpgradeResult>;

export function RequestFleetAgentUpgrade(arg1:main.FleetUpgradeRequest):Promise<main.FleetUpgradeResult>;

export function RequestGitSync():Promise<main.GitSyncResult>;

export function SaveProfile(arg1:main.ConnectionProfile):Promise<void>;

export function SetEndpointLabel(arg1:main.EndpointLabelSetRequest):Promise<main.EndpointLabelResultView>;
