// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateSecretVersion(arg1:main.SecretLifecycleRequest):Promise<main.SecretVersionView>;

export function AuthorizeChangeRequest(arg1:main.ChangeAuthorizationRequest):Promise<main.ChangeActionResult>;

export function BootstrapProfile(arg1:main.ConnectionProfile,arg2:string):Promise<main.ConnectionView>;

export function BuildLocalPackage():Promise<main.AppPackageArchiveView>;

export function ChangeRequestLifecycle(arg1:main.ChangeLifecycleRequest):Promise<main.ChangeActionResult>;

export function ChooseAppPackageArchive():Promise<main.AppPackageArchiveView>;

export function ChooseBaselineAdoptionPlan(arg1:string):Promise<main.BaselineAdoptionPreview>;

export function ChooseLocalPackageSource():Promise<main.LocalPackageView>;

export function ClearDeploymentToken():Promise<void>;

export function ClearEnrollmentToken():Promise<void>;

export function ConnectProfile(arg1:main.ConnectionProfile):Promise<main.ConnectionView>;

export function CopyDeploymentToken():Promise<void>;

export function CopyEnrollmentToken():Promise<void>;

export function CreateBaselineAdoption(arg1:main.BaselineAdoptionRequest):Promise<main.ChangeActionResult>;

export function CreateDeploymentToken(arg1:main.DeploymentTokenCreateRequest):Promise<main.DeploymentTokenCreateResult>;

export function CreateEnrollmentToken(arg1:main.EnrollmentTokenRequest):Promise<main.EnrollmentTokenResult>;

export function CreateLocalPackage(arg1:main.LocalPackageCreateRequest):Promise<main.LocalPackageView>;

export function DeleteAppPackage(arg1:main.AppPackageDeleteRequest):Promise<main.AppPackageDeleteResult>;

export function GetApplicationInfo():Promise<main.ApplicationInfo>;

export function GetDiagnosticCapabilities():Promise<main.DiagnosticCapabilities>;

export function ListAppPackages(arg1:string):Promise<Array<main.AppPackageView>>;

export function ListDeploymentTokens():Promise<Array<main.DeploymentTokenView>>;

export function ListSecretVersions(arg1:string):Promise<Array<main.SecretVersionView>>;

export function LoadActivityPage(arg1:main.ActivityPageRequest):Promise<main.ActivityPageView>;

export function LoadAppPackage(arg1:string,arg2:string):Promise<main.AppPackageView>;

export function LoadAssetInventory():Promise<main.AssetInventoryView>;

export function LoadAuditExportInfo():Promise<main.AuditExportInfoView>;

export function LoadChangeRequestDetail(arg1:string):Promise<main.ChangeRequestDetailView>;

export function LoadDeploymentToken(arg1:string):Promise<main.DeploymentTokenView>;

export function LoadDiagnosticRequest(arg1:string):Promise<main.DiagnosticLifecycleView>;

export function LoadEndpointDetail(arg1:string):Promise<main.EndpointDetailView>;

export function LoadFirewallReport(arg1:string):Promise<main.FirewallReportView>;

export function LoadFleetDetail(arg1:string):Promise<main.FleetDetailView>;

export function LoadFleetOperationalReports(arg1:string):Promise<main.FleetOperationalReportsView>;

export function LoadProfiles():Promise<Array<main.ConnectionProfile>>;

export function LoadWorkspace():Promise<main.WorkspaceView>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function PromoteChangeBaseline(arg1:main.ChangeBaselinePromotionRequest):Promise<main.ChangeActionResult>;

export function PublishAppPackage(arg1:main.AppPackagePublishRequest):Promise<main.AppPackageView>;

export function RemoveEndpoint(arg1:main.EndpointRemovalRequest):Promise<main.EndpointRemovalResult>;

export function RemoveEndpointLabel(arg1:main.EndpointLabelRemoveRequest):Promise<main.EndpointLabelResultView>;

export function RequestDiagnosticCollection(arg1:main.DiagnosticCollectionRequest):Promise<main.DiagnosticCollectionResult>;

export function RequestEndpointAgentUpgrade(arg1:main.EndpointUpgradeRequest):Promise<main.EndpointUpgradeResult>;

export function RequestFleetAgentUpgrade(arg1:main.FleetUpgradeRequest):Promise<main.FleetUpgradeResult>;

export function RequestGitSync():Promise<main.GitSyncResult>;

export function RevokeDeploymentToken(arg1:main.DeploymentTokenRevokeRequest):Promise<main.DeploymentTokenView>;

export function RevokeSecretVersion(arg1:main.SecretLifecycleRequest):Promise<main.SecretVersionView>;

export function SaveAssetInventory(arg1:string):Promise<main.ReadExportSaveResult>;

export function SaveDeploymentToken(arg1:string):Promise<main.DeploymentTokenSaveResult>;

export function SaveDiagnosticBundle(arg1:string):Promise<main.DiagnosticBundleSaveResult>;

export function SaveFirewallReport(arg1:main.FirewallExportRequest):Promise<main.ReadExportSaveResult>;

export function SaveProfile(arg1:main.ConnectionProfile):Promise<void>;

export function SetEndpointLabel(arg1:main.EndpointLabelSetRequest):Promise<main.EndpointLabelResultView>;

export function UploadSecretVersion(arg1:main.SecretUploadRequest):Promise<main.SecretVersionView>;
